/*
 * JFileChooserTest.java
 *
 * Created on __DATE__, __TIME__
 */

package org.apache.demo.test;

import javax.swing.JFileChooser;

import prefuse.util.ui.UILib;

/**
 *
 * @author  __USER__
 */
public class JFileChooserTest extends javax.swing.JFrame {

	private static boolean isEnable = false;
	/** Creates new form JFileChooserTest */
	public JFileChooserTest() {
		initComponents();
		jMenu1.setEnabled(isEnable);
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		button1 = new java.awt.Button();
		jButton1 = new javax.swing.JButton();
		jMenuBar1 = new javax.swing.JMenuBar();
		jMenu1 = new javax.swing.JMenu();
		jMenuItem1 = new javax.swing.JMenuItem();
		jMenu2 = new javax.swing.JMenu();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		button1.setLabel("button1");
		button1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				button1ActionPerformed(evt);
			}
		});

		jButton1.setText("jButton1");
		jButton1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton1ActionPerformed(evt);
			}
		});

		jMenu1.setText("File");

		jMenuItem1.setText("Item");
		jMenu1.add(jMenuItem1);

		jMenuBar1.add(jMenu1);

		jMenu2.setText("Edit");
		jMenuBar1.add(jMenu2);

		setJMenuBar(jMenuBar1);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup().addContainerGap(184, Short.MAX_VALUE).addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(jButton1).addComponent(button1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)).addGap(135, 135, 135)));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout.createSequentialGroup().addGap(79, 79, 79).addComponent(button1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE).addGap(39, 39, 39).addComponent(jButton1).addContainerGap(110, Short.MAX_VALUE)));

		pack();
	}// </editor-fold>
	//GEN-END:initComponents

	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
		jMenu1.setEnabled(true);
	}

	private void button1ActionPerformed(java.awt.event.ActionEvent evt) {
		JFileChooser jch = new JFileChooser();
		jch.setDialogTitle("open file");
		jch.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);//只显示文件夹
		//		int result = jch.showOpenDialog(this);
		//		int result = jch.showDialog(this,"jack"); 可以将"打开"或"保存"编程jack
		int result = jch.showOpenDialog(this);
		if (result == JFileChooser.APPROVE_OPTION) {
			System.out.println("选中的文件夹为：" + jch.getSelectedFile().getAbsolutePath());
			System.out.println("打开文件成功");
		}

	}

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		UILib.setPlatformLookAndFeel();
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new JFileChooserTest().setVisible(true);
			}
		});
	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private java.awt.Button button1;
	private javax.swing.JButton jButton1;
	private javax.swing.JMenu jMenu1;
	private javax.swing.JMenu jMenu2;
	private javax.swing.JMenuBar jMenuBar1;
	private javax.swing.JMenuItem jMenuItem1;
	// End of variables declaration//GEN-END:variables

}