/*
 * DatabaseConfFrame.java
 *
 * Created on __DATE__, __TIME__
 */

package org.apache.demo;

import java.sql.SQLException;

import prefuse.Visualization;
import prefuse.data.Graph;
import prefuse.data.Table;
import prefuse.data.io.DataIOException;
import prefuse.data.io.sql.ConnectionFactory;
import prefuse.data.io.sql.DatabaseDataSource;
import prefuse.util.ui.UILib;
import prefuse.visual.VisualGraph;

/**
 *
 * @author  Jack
 */
public class DatabaseConfFrame extends javax.swing.JFrame {
	
	public static DatabaseConfFrame dbFrame = null;
	private Visualization visInstance = null;
	public static DatabaseConfBean dbConfig = new DatabaseConfBean(); 

	/** Creates new form DatabaseConfFrame */
	public DatabaseConfFrame() {
		initComponents();
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jPanel1 = new javax.swing.JPanel();
		strConfLabel = new java.awt.Label();
		databaseLabel = new java.awt.Label();
		usernameLabel = new java.awt.Label();
		pwdLabel = new java.awt.Label();
		portLabel = new java.awt.Label();
		nodeSelectLabel = new java.awt.Label();
		edgeSelectLabel = new java.awt.Label();
		strConfText = new java.awt.TextField();
		databaseText = new java.awt.TextField();
		usernameText = new java.awt.TextField();
		pwdText = new java.awt.TextField();
		portText = new java.awt.TextField();
		nodeSelectText = new java.awt.TextField();
		edgeSelectText = new java.awt.TextField();
		confButton = new java.awt.Button();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		strConfLabel.setFont(new java.awt.Font("微软雅黑", 0, 12));
		strConfLabel.setText("Driver String");

		databaseLabel.setFont(new java.awt.Font("微软雅黑", 0, 12));
		databaseLabel.setText("Database Label");

		usernameLabel.setFont(new java.awt.Font("微软雅黑", 0, 12));
		usernameLabel.setText("Username");

		pwdLabel.setFont(new java.awt.Font("微软雅黑", 0, 12));
		pwdLabel.setText("Password");

		portLabel.setFont(new java.awt.Font("微软雅黑", 0, 12));
		portLabel.setText("Port");

		nodeSelectLabel.setFont(new java.awt.Font("微软雅黑", 0, 12));
		nodeSelectLabel.setText("Search Nodes");

		edgeSelectLabel.setFont(new java.awt.Font("微软雅黑", 0, 12));
		edgeSelectLabel.setText("Search Edges");

		strConfText.setText("com.microsoft.sqlserver.jdbc.SQLServerDriver");

		confButton.setFont(new java.awt.Font("微软雅黑", 0, 12));
		confButton.setLabel("OK");
		confButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				confButtonActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout.setHorizontalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				jPanel1Layout.createSequentialGroup().addGroup(
						jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(
								jPanel1Layout.createSequentialGroup().addGap(42, 42, 42).addGroup(
										jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(databaseLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE).addComponent(strConfLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE).addComponent(usernameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE).addComponent(pwdLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE).addComponent(portLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE).addComponent(nodeSelectLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE).addComponent(edgeSelectLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)).addGap(19, 19, 19).addGroup(
										jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(edgeSelectText, javax.swing.GroupLayout.DEFAULT_SIZE, 267, Short.MAX_VALUE).addComponent(nodeSelectText, javax.swing.GroupLayout.DEFAULT_SIZE, 267, Short.MAX_VALUE).addComponent(portText, javax.swing.GroupLayout.DEFAULT_SIZE, 267, Short.MAX_VALUE).addComponent(pwdText, javax.swing.GroupLayout.DEFAULT_SIZE, 267, Short.MAX_VALUE).addComponent(usernameText, javax.swing.GroupLayout.DEFAULT_SIZE, 267, Short.MAX_VALUE).addComponent(databaseText, javax.swing.GroupLayout.DEFAULT_SIZE, 267, Short.MAX_VALUE).addComponent(strConfText, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)))
								.addGroup(jPanel1Layout.createSequentialGroup().addGap(166, 166, 166).addComponent(confButton, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))).addContainerGap()));
		jPanel1Layout.setVerticalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				jPanel1Layout.createSequentialGroup().addGap(36, 36, 36).addGroup(
						jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(jPanel1Layout.createSequentialGroup().addComponent(strConfText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(databaseText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(usernameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)).addGroup(
								jPanel1Layout.createSequentialGroup().addComponent(strConfLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(databaseLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(usernameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addGroup(
						jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(
								jPanel1Layout.createSequentialGroup().addComponent(pwdText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(portText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(nodeSelectText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(edgeSelectText, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)).addGroup(
								jPanel1Layout.createSequentialGroup().addComponent(pwdLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(portLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(nodeSelectLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(edgeSelectLabel, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))).addGap(33, 33, 33).addComponent(confButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE).addContainerGap(27, Short.MAX_VALUE)));

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));

		pack();
	}// </editor-fold>
	//GEN-END:initComponents

	private void confButtonActionPerformed(java.awt.event.ActionEvent evt) {
		
		visInstance = GraphUtils.getVisualization();
		
		dbConfig.setStrConfig(strConfText.getText());
		dbConfig.setDatabase(databaseText.getText());
		dbConfig.setUsername(usernameText.getText());
		dbConfig.setPwd(pwdText.getText());
		dbConfig.setPortNumber(portText.getText());
		dbConfig.setNodeSql(nodeSelectText.getText());
		dbConfig.setEdgeSql(edgeSelectText.getText());
		
		String driver = dbConfig.getStrConfig();
		String url = "jdbc:sqlserver://localhost:"+dbConfig.getPortNumber()+";DatabaseName="+dbConfig.getDatabase().toString()+"";
		String username = dbConfig.getUsername();
		String password = dbConfig.getPwd();
		DatabaseDataSource dbds = null;
		try {
			dbds = ConnectionFactory.getDatabaseConnection(driver, url, username, password);
		} catch (SQLException e1) {
			e1.printStackTrace();
		} catch (ClassNotFoundException e1) {
			e1.printStackTrace();
		}
		System.out.println(dbConfig.getEdgeSql());
		Table nodes = null;
		Table edges = null;
		try {
			nodes = dbds.getData(dbConfig.getNodeSql());
			edges = dbds.getData(dbConfig.getEdgeSql());
		} catch (DataIOException e) {
			e.printStackTrace();
		}
		Graph graph = new Graph(nodes, edges, false, "id", "sid", "tid");
//		Table t = graph.getNodeTable();
//		int cc = t.getColumnCount();
//		strings = new String[cc];
//		for (int i = 0; i < cc; ++i) {
//			strings[i] = t.getColumnName(i);
//		}
		
		visInstance.add("graph", graph);
		
		dbFrame.dispose();
		
		GraphUtils.setRenderer();
		
		GraphUtils.setAction();
//		FileTabUtils.preShow();
		
		MainFrame mainFrame = new MainFrame();
		mainFrame.sendToJSplitPane();
		
	}

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		UILib.setPlatformLookAndFeel();
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				dbFrame = new DatabaseConfFrame();
				dbFrame.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
				dbFrame.setVisible(true);
			}
		});
	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private java.awt.Button confButton;
	private java.awt.Label databaseLabel;
	private java.awt.TextField databaseText;
	private java.awt.Label edgeSelectLabel;
	private java.awt.TextField edgeSelectText;
	private javax.swing.JPanel jPanel1;
	private java.awt.Label nodeSelectLabel;
	private java.awt.TextField nodeSelectText;
	private java.awt.Label portLabel;
	private java.awt.TextField portText;
	private java.awt.Label pwdLabel;
	private java.awt.TextField pwdText;
	private java.awt.Label strConfLabel;
	private java.awt.TextField strConfText;
	private java.awt.Label usernameLabel;
	private java.awt.TextField usernameText;
	// End of variables declaration//GEN-END:variables

}